name: CI Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine  # Usando uma imagem leve baseada em Alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --network-timeout 600000
      
      - name: Run tests
        run: yarn test:e2e
